name: ㅊ
strokes:
  - points: [[3, 0], [7, 0]]           # 윗선 (y = 0)
  - points: [[0, 2], [10, 2]]          # 가로선 (y = 2)
  - points: [[10, 2], [0, 8]]         # 왼대각선
  - points: [[5, 5], [10, 8]]         # 오른대각선
z_offset: 5.0
