name: ㄸ
strokes:
  - points:
      - [0, 0]
      - [5, 0]
  - points:
      - [0, 0]
      - [0, 8]
      - [5, 8]
  - points:
      - [5, 0]
      - [10, 0]
  - points:
      - [5, 0]
      - [5, 8]
      - [10, 8]
    

z_offset: 5.0