name: ㄲ
strokes:
  - points:
      - [0, 0]
      - [5, 0]
  - points:
      - [5, 0]
      - [5, 5]
  - points:
      - [5, 0]
      - [10, 0]
  - points:
      - [10, 0]
      - [10, 5]

z_offset: 5.0