name: ㅎ
strokes:
  - points:
      - [2, 0]      # [0+2, -4+4]
      - [6, 0]      # [4+2, -4+4]

  - points:
      - [0, 2]      # [-2+2, -2+4]
      - [8, 2]      # [6+2, -2+4]

  - points:
      - [2, 4]      # [0+2, 0+4]
      - [0, 6]      # [-2+2, 2+4]
      - [0, 10]     # [-2+2, 6+4]
      - [2, 12]     # [0+2, 8+4]
      - [6, 12]     # [4+2, 8+4]
      - [8, 10]     # [6+2, 6+4]
      - [8, 6]      # [6+2, 2+4]
      - [6, 4]      # [4+2, 0+4]
      - [2, 4]      # [0+2, 0+4] (닫힘점)
z_offset: 5.0
