name: ㅉ
strokes:
  - points: [[0, 0], [5, 0]]
  - points: [[5, 0], [0, 8]]
  - points: [[2.5, 4], [5, 8]]
  - points: [[5, 0], [10, 0]]
  - points: [[10, 0], [5, 8]]
  - points: [[7.5, 4], [10, 8]]
  
z_offset: 5.0