name: ㅇ
strokes:
  - points:
      - [5.5, 0.0]
      - [2.31, 0.77]
      - [0.77, 2.31]
      - [0.0, 5.5]
      - [0.77, 8.69]
      - [2.31, 10.23]
      - [5.5, 11.0]
      - [8.69, 10.23]
      - [10.23, 8.69]
      - [11.0, 5.5]
      - [10.23, 2.31]
      - [8.69, 0.77]
      - [5.5, 0.0]
    z_offset: 5.0
