name: ㅍ
strokes:
  - points: [[0, 1],  [10, 1]]    # 윗 가로선 (y = 2)
  - points: [[3, 1],  [3, 10]]    # 왼쪽 세로선
  - points: [[7, 1],  [7, 10]]    # 오른쪽 세로선
  - points: [[0, 10], [10, 10]]   # 아랫 가로선 (y = 12)
z_offset: 5.0
