name: ㅘ
strokes:
  # ㅗ 구성 (세로 + 가로 + 오른쪽 세로)
  - points: [[5.0, 4.0], [5.0, 8.0]]        # 세로획
  - points: [[0.0, 8.0], [10.0, 8.0]]       # 가로획
  - points: [[10.0, 0.0], [10.0, 13.0]]     # 오른쪽 세로획 (ㅏ 역할)
  - points: [[10.0, 5.0], [13.0, 5.0]]
z_offset: 5.0
