name: ㅙ
strokes:
  - points: [[3.8, 3.9], [3.8, 10.4]]
  - points: [[0.0, 10.4], [10.0, 10.4]]
  - points: [[10.0, 0.0], [10.0, 13.0]]
  - points: [[10.0, 6.5], [12.7, 6.5]]
  - points: [[12.7, 0.0], [12.7, 13.0]]
z_offset: 5.0
