name: ㅞ
strokes:
  - points: [[0.0, 8.0], [10.0, 8.0]]        # 가로획 (기준선)
  - points: [[5.0, 8.0], [5.0, 13.0]]        # 중앙 세로획
  - points: [[6.5, 10.0], [10.0, 10.0]]
  - points: [[10.0, 0.0], [10.0, 13.0]]
  - points: [[12.0, 0.0], [12.0, 13.0]] 
z_offset: 5.0
