name: ㅕ
strokes:
  - points: [[0, 4], [2, 4]]       # 첫 가로획 (y=0 → y=3으로 +3 보정)
  - points: [[0, 8], [2, 8]]       # 두 번째 가로획 (y=4 → y=7으로 +3 보정)
  - points: [[2, 0], [2, 13]]      # 세로획 (y=-3~7 → 0~10으로 +3 보정)
z_offset: 5.0
